### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by tobil4sk** [Aidan63/hxcpp_asys#94]
Hi, I'd like to test out these asys bindings. I'm guessing the code in this repository is MIT, since the plan is for it to go into the Haxe std, but just wanted to double check as there's currently no LICENSE file.

**Comment by Aidan63** [comment]
Yes, MIT is fine, I've just committed a license.

**Comment by tobil4sk** [comment]
Thanks! And thank you for your work on this project.
